version: '3.9'

services:
  acquirer.api:
    image: ${DOCKER_REGISTRY-}acquirerapi
    container_name: "acquirer.api"
    build:
      context: .
      dockerfile: Acquirer.API\Dockerfile
    depends_on:
      - mssql
    ports:
      - 80
      - 443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: "acquirer.dal"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
